### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/emacs-lisp#191]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/emacs-lisp/runs/3371983221

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by maurelio1234** [comment]
Hi, @ErikSchierboom I'd like to take a look at this.

**Comment by maurelio1234** [comment]
Is it possible to assign me to this issue?

**Comment by ErikSchierboom** [comment]
Done

**Comment by fapdash** [comment]
@ErikSchierboom Looks like this can be closed.
