### ISSUE TITLE
Core libraries need to be imported manually

### ISSUE THREAD

**Issue by dschrempf** [exercism/emacs-lisp#198]
Solutions using functions such as `seq-filter`, or `string-empty-p` succeed locally but fail in the browser because the libraries are not automatically imported (`require`d).  Which libraries are imported by default?

**Comment by fapdash** [comment]
@dschrempf I recommend installing [Flycheck](https://www.flycheck.org/en/latest/user/installation.html), which will inform you if you have to require additional packages.
The error to look out for is `the function ‘the-function’ is not known to be defined.`.

I added instructions on how to set up Flycheck in https://github.com/exercism/emacs-lisp/pull/231.

**Comment by dschrempf** [comment]
I do use flycheck in my Emacs setup, but it didn't warn me for these functions, I guess because they are loaded in my setup but not in the browser one.

Not sure if this issue can be solved in a satisfying way, because the local setup will always differ from the one in the browser. I think it would help if we provide the exact features that are loaded in the browser version.

**Comment by fapdash** [comment]
Mh, weird, in my setup flycheck complains as soon as I remove the `require` statement from the solution file and the respective package is loaded into my Emacs.

I think it's fair to assume that no package is loaded in the browser version, so only functions defined in the C code should be available by default? Will have to investigate more..

**Comment by ErikSchierboom** [comment]
This is how we build the emacs lisp test runner: https://github.com/exercism/emacs-lisp-test-runner/blob/main/Dockerfile
If there are common packages that students often used, it's totally reasonable to add them to that file. 

Maybe you two could discuss which packages would make sense to include?
