### ISSUE TITLE
Documentation for interactive testing

### ISSUE THREAD

**Issue by scmbradley** [exercism/emacs-lisp#205]
There were a few bits of how to run tests for emacs lisp interactively that aren't well-explained on the [help page](https://exercism.org/docs/tracks/emacs-lisp/tests). First, `ert` won't do anything until you `eval-buffer` on the `-test.el` file. Second, if you make a change to the source file, you need to `eval-buffer` on that file in order for `ert` to be testing the version you just changed. I think it would help to spell out these steps in a little more detail?

**Comment by hut8** [comment]
I just found the help page which you linked to (I was just looking at HELP.md which makes absolutely no mention of this). For someone on "hello world" for emacs lisp, we can't be expected to know how to eval-buffer. This should definitely be right in HELP.md but instead it lists 4 ways that will not actually run any tests without eval'ing the buffer.
