### ISSUE TITLE
Exercism test runner cannot locate Emacs functions that work on my local machine

### ISSUE THREAD

**Issue by randre03** [exercism/emacs-lisp#239]
There have been several exercises which pass all tests on my local machine, but fail exercism's emacs lisp test runner. It is clear from the backtraces that these errors are caused by the existence of functions emacs-lisp thinks are void (do not exist). This then causes me to recreate these "missing" functions for the code to pass. Two that I can think of readily are ` string-pad` and `string-join`.

BTW, I am running Doom Emacs (Emacs v. 28.2) on Manjaro. Thanks!

**Comment by fapdash** [comment]
@randre03 Hey there, these functions are part of the `subr-x` package, which means you have to require it for your code to run in the test runner. You can use `Ctrl+h f` -> enter function name -> `RET` to check which packages defines a particular function. Doom Emacs probably loads `subr-x` as part of your Emacs init process, so locally your tests run fine.
