### ISSUE TITLE
New maintainer for this track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/emacs-lisp#246]
@fapdash I noticed that you've been doing work on this track lately.
Would you be interested in having write-access to the repository in order to make progress on it?

I've approved the open PRs that you've submitted, and if you accept write-access on the repo, I'll let you merge them. If not, I'll go ahead and merge them myself.

**Comment by fapdash** [comment]
@kytrinyx Sure, that would speed things up. Please go ahead and give me write-access.
I had a meeting with Jonathan this week about becoming a maintainer and I accepted. :)

I noticed the pattern in Exercism repositories that people will approve a PR but still wait a couple of days before they merge. Is this so other people in the community can also review and give feedback, if they want to? Should I follow this example?

**Comment by kytrinyx** [comment]
@fapdash That's great, thank you! I'm so glad you were able to connect with Jonathan.

You should have an invite for the team.

In terms of process, we tend to do the following:
- if the person who created the PR is also a maintainer on the same repository, approve, but let the other person merge
- if you think it would be useful to get an extra pair of eyes on the PR, wait a couple of days (maybe ping people specifically), then just merge if nobody seems to have any objections

Also, feel free to jump in the forum as well to chat with other maintainers here: https://forum.exercism.org/c/exercism/building-exercism/125
