### ISSUE TITLE
Configlet sync CI is broken

### ISSUE THREAD

**Issue by BNAndras** [exercism/emacs-lisp#359]
@ErikSchierboom, we have a GHA that regularly uses configlet to check for unsynced files at https://github.com/exercism/emacs-lisp/actions/workflows/configlet-sync.yml, but it's been broken for over a year due to rate limits. Is this something fixable?

**Comment by ErikSchierboom** [comment]
Maybe check the logs to see if https://github.com/exercism/emacs-lisp/blob/main/.github/workflows/configlet-sync.yml#L17-L23 does indeed do an authenticated request? Or else simulate that locally.

Looking at CI, it looks like what is failing is the issue creation. Maybe check if the authentication is working there? Or else try updating the workflow?

**Comment by fapdash** [comment]
If we find a solution we should also fix it for the common-lisp track, which has the same job and issue: https://github.com/exercism/common-lisp/blob/c35edf8095e87c64b9c2f22ea08a2da7024a3411/.github/workflows/configlet-sync.yml

**Comment by kmarker1101** [comment]
this may be a long standing issue with create-an-issue

https://github.com/JasonEtco/create-an-issue/issues/142

**Comment by fapdash** [comment]
> Same error here. It seems to be triggered easily when using the "update_existing: true" parameter, so the search/issues endpoint is the one affected by the secondary rate limit.

https://github.com/JasonEtco/create-an-issue/issues/142#issuecomment-2066826259

We probably could get rid of this setting as we're closing the issue each time.
