### ISSUE TITLE
generate_practice_exercise

### ISSUE THREAD

**Issue by kmarker1101** [exercism/emacs-lisp#419]
I have noticed that when I run this script, the ert tests frequently have a non valid name. Something like:

`(ert-deftest combination-of-lower-and-uppercase-letters,-punctuation-and-white-space ())`

So obviously the comma should not be there. This is not a huge issue but I just thought I would document it incase we want to fix it.

**Comment by fapdash** [comment]
@kmarker1101 Thanks for reporting! Should be fixed. :)
